import { HttpStatus } from '@nestjs/common';

export class AppError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly status: HttpStatus = HttpStatus.BAD_REQUEST,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export const ErrorCodes = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  AUTH_INVALID_SESSION: 'AUTH_INVALID_SESSION',
  AUTH_REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  OTP_DELIVERY_FAILED: 'OTP_DELIVERY_FAILED',
  WALLET_INSUFFICIENT_FUNDS: 'WALLET_INSUFFICIENT_FUNDS',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',
  CALL_INVALID_TRANSITION: 'CALL_INVALID_TRANSITION',
  CALL_NOT_PARTICIPANT: 'CALL_NOT_PARTICIPANT',
  CALL_ALREADY_ACTIVE: 'CALL_ALREADY_ACTIVE',
  CALL_RTC_FORBIDDEN: 'CALL_RTC_FORBIDDEN',
  CALL_RTC_FAILED: 'CALL_RTC_FAILED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_BUSY: 'USER_BUSY',
  HOST_OFFLINE: 'HOST_OFFLINE',
  HOST_BUSY: 'HOST_BUSY',
  HOST_NOT_APPROVED: 'HOST_NOT_APPROVED',
  HOST_NOT_ACTIVE: 'HOST_NOT_ACTIVE',
  HOST_NOT_DISCOVERABLE: 'HOST_NOT_DISCOVERABLE',
  HOST_UNAVAILABLE: 'HOST_UNAVAILABLE',
  HOST_CALL_TYPE_DISABLED: 'HOST_CALL_TYPE_DISABLED',
  HOST_APPLICATION_EXISTS: 'HOST_APPLICATION_EXISTS',
  HOST_APPLICATION_INVALID: 'HOST_APPLICATION_INVALID',
  HOST_INCOMPLETE: 'HOST_INCOMPLETE',
  HOST_VERIFICATION_REQUIRED: 'HOST_VERIFICATION_REQUIRED',
  HOST_AGREEMENT_REQUIRED: 'HOST_AGREEMENT_REQUIRED',
  HOST_SUSPENDED: 'HOST_SUSPENDED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_FORBIDDEN: 'CONVERSATION_FORBIDDEN',
  MESSAGE_INVALID: 'MESSAGE_INVALID',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  MESSAGE_RATE_LIMITED: 'MESSAGE_RATE_LIMITED',
  MESSAGE_BLOCKED: 'MESSAGE_BLOCKED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  SOCKET_UNAUTHORIZED: 'SOCKET_UNAUTHORIZED',
  SOCKET_ROOM_FORBIDDEN: 'SOCKET_ROOM_FORBIDDEN',
  PAYOUT_NOT_ELIGIBLE: 'PAYOUT_NOT_ELIGIBLE',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
